import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bem-vindo ao <a href="https://instagram.com/projetoceos">Projeto Céos</a>
        </h1>

        <p className={styles.description}>
          aprenda e torne-se um developer
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentação &rarr;</h2>
            <p>Base de conhecimento do Projeto</p>
          </a>

          <a href="/reviews" className={styles.card}>
            <h2>Avaliações &rarr;</h2>
            <p>Um CRUD de avaliações</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Blog &rarr;</h2>
            <p>Um exemplo de um Blog</p>
          </a>

          <a
            href="https://borafazertrilha.com/"
            className={styles.card}
          >
            <h2>Sobre &rarr;</h2>
            <p>
              Um exemplo de página 
            </p>
          </a>
        </div>
      </main>


    </div>
  )
}
